### PR TITLE
Fix progress reporting when completed

### PR DESCRIPTION
**Pull request by larryonoff**
The library doesn't report Progress when completed or reports with huge delay. So I've implemented quick-fix. Please review.

### CODE REVIEW

**Comment by YuAo** [comment]
Hi @larryonoff thanks for the PR. 

I'm not sure we should report a 100% progress here. In fact, we should **not** report the export is completed when the video reading is just finished (there may be audios, and the asset writer may still have work to do, etc).

My suggestion is to use the completion handler. Do not rely on the progress handler to report a 100% progress. 

However, if you do want to report a 100% progress. How about we pass the progressHandler **and** the completionHandler to the `finish` function, report the progress just before we call completion?
```Swift
private func finish(progressHandler: ((Progress) -> Void)? ,completionHandler: @escaping (Swift.Error?) -> Void) {
        ...
           self.writer.finishWriting { [weak self] in
                guard let strongSelf = self else { return }
                if strongSelf.writer.status == .failed {
                    try? FileManager().removeItem(at: strongSelf.outputURL)
                }
                // Maybe report 100% completion here?
                if strongSelf.writer.error != nil {
                    DispatchQueue.main.async {
                        if let progress = self.progress {
                            progress.completedUnitCount = progress.totalUnitCount
                            self.progressHandler?(progress)
                        }
                    }
                }
                strongSelf.dispatchCallback(with: strongSelf.writer.error, completionHandler)
            }
       ...
```

Also we should make sure the progress reported at the video encoding path does not fully complete, so that framework users may rely on the one and only `progress == 1` logic.
```
let units = Int64((CMSampleBufferGetPresentationTimeStamp(buffer) - self.configuration.timeRange.start).seconds * 999)

// I'm not satisfy with the "999" here. However let's focus on the progress reporting first.
```

**Comment by larryonoff** [comment]
@YuAo our application shows export progress, so as result progress halts on ~0,9 and suddenly completes then. This is not acceptable by our design team.

> My suggestion is to use the completion handler. Do not rely on the progress handler to report a 100% progress.
I tried completion handler already, but there's a lag that isn't also acceptable.

> How about we pass the progressHandler and the completionHandler to the finish function
I like the ideal. Let me check it out.

**Comment by larryonoff** [comment]
> How about we pass the progressHandler and the completionHandler to the finish function

finish function is too late. So lag exists.

@YuAo please check the latest changes. If there're OK, I'll do some code cleanup and merge.

**Comment by YuAo** [comment]
The fact is that there is actually a gap between video reading completion and the export completion. We cannot get any progress for the writer's finishWriting part. So the nature of the export progress is not smooth. 

I don't think this is a problem the framework should handle. The framework should report information as accurate as it possibly can, that means it cannot report a progress of 1 when asset writer's writing is not finished.

**Comment by YuAo** [comment]
I think maybe we can give the `progress` object a hint that all video reading is completed so you can update your progress displayed to user to 1.0 and wait for the completion handler.

**Comment by larryonoff** [comment]
> The fact is that there is actually a gap between video reading completion and the export completion. We cannot get any progress for the writer's finishWriting part. So the nature of the export progress is not smooth.
> 
> I don't think this is a problem the framework should handle. The framework should report information as accurate as it possibly can, that means it cannot report a progress of 1 when asset writer's writing is not finished.

The idea of any framework is to hide any internal work, so a developer as a framework user cannot change internal functionality.

The VideoIO framework has functionality that reports progress, but it isn't accurate. As result the progress reporting logic is useless. Nevertheless there're internal framework assumptions that can make progress better. I don't see any reasons why it should not be implemented.

PS. I think every iOS developer familiar with how Apple (or other big companies) implements their frameworks with unexpected behaviors. That fixed later or never.

**Comment by larryonoff** [comment]
> I think maybe we can give the `progress` object a hint that all video reading is completed so you can update your progress displayed to user to 1.0 and wait for the completion handler. What do you think?

I'm not sure that I understand this suggestion, but I assume that the issue is connected with `input.markAsFinished()`. This function blocks the thread for some short period of time. So the end progress (=1.0) will never be smooth if progress handler is called after.

**Comment by larryonoff** [comment]
I believe that the latest changes I've pushed covers your concerns.

**Comment by YuAo** [comment]
> PS. I think every iOS developer familiar with how Apple (or other big companies) implements their frameworks with unexpected behaviors. That fixed later or never.

I totally agree with you.

That's why I cannot accept that we report a 100% completed progress before the asset writer finishes the writing. 

Whenever you see an operation that has a 100% completed progress you are expecting that the operation is **finished** and the result is **usable**. 

However based on your current implementation when a 100% progress is reported, neither the export operation is finished nor the video at the output url is usable. This creates the "unexpected behavior". That's what I am trying to avoid.

**Comment by larryonoff** [comment]
> > PS. I think every iOS developer familiar with how Apple (or other big companies) implements their frameworks with unexpected behaviors. That fixed later or never.
> 
> I totally agree with you.
> 
> That's why I cannot accept that we report a 100% completed progress before the asset writer finishes the writing.
> 
> Whenever you see an operation that has a 100% completed progress you are expecting that the operation is **finished** and the result is **usable**.
> 
> However based on your current implementation when a 100% progress is reported, neither the export operation is finished nor the video at the output url is usable. This creates the "unexpected behavior". That's what I am trying to avoid.

what do you think about reporting `0.9999` then instead of `1.0` ?

**Comment by YuAo** [comment]
I think the underlying problem here is that you only care about video reading/encoding progress. You don't really care about the finish writing part.

So my suggestion is to make some child progresses that reflect the progress of internal stages of the exporter. So you can query progress for each stage.

Maybe we should use a progress tree: https://developer.apple.com/documentation/foundation/progress#1661050

**Comment by YuAo** [comment]
Here's my workaround: https://github.com/MetalPetal/VideoIO/pull/7

**Comment by larryonoff** [comment]
@YuAo I like progress tree idea. I just not sure that NSProgress in general works fine :)

**Comment by larryonoff** [comment]
> Here's my workaround: #7

looks really great!

What about adding some of the additions below?
```objective-c
typedef NSString * NSProgressKind NS_EXTENSIBLE_STRING_ENUM;
typedef NSString * NSProgressUserInfoKey NS_EXTENSIBLE_STRING_ENUM;
typedef NSString * NSProgressFileOperationKind NS_EXTENSIBLE_STRING_ENUM;
```

**Comment by YuAo** [comment]
The progress kind and file operation kind is not suitable here. Exporting an asset is not any of the predefined file operation (copying, receiving, downloading, decompressing after downloading).

**Comment by larryonoff** [comment]
> The progress kind and file operation kind is not suitable here. Exporting an asset is not any of the predefined file operation (copying, receiving, downloading, decompressing after downloading).

But you can extend it with your own.

**Comment by YuAo** [comment]
If you use one of the predefined type, the system will create the `localizedDescription` based on the kind and file info.
I can't see any benefits of extending these types.

**Pull request closed without merging**
