### PR TITLE
Make the lifecycle of `AssetExportSession` more predictable.

### LINKED ISSUE #8: AssetExportSession still exist in memory after cancel
During debugging I've observed the following issue.

1. AssetExportSession.export
2. AssetExportSession.cancel 
3. maybe repeat 1 and 2 several times.

As result `videoInput.requestMediaDataWhenReady(on: self.queue) { [weak self] in` line 307 still running, but `self = nil`.

### PR DESCRIPTION
**Pull request by YuAo**
- An `AssetExportSession` is guaranteed to be alive between `export` call and the `completion` handler.
- If nothing holds an `AssetExportSession` it will `deinit` after the `completion` handler is called.

This fixes #8

### CODE REVIEW

**Comment by YuAo** [comment]
@larryonoff Can give this a try and see if the issue is fixed.

**Comment by larryonoff** [comment]
@YuAo thanks! trying it.

**Comment by larryonoff** [comment]
Looks much better. But we were able to reproduce the case when `videoInput.requestMediaDataWhenReady` still working after cancelling.

I'm investigating the case.

**Comment by YuAo** [comment]
> Looks much better. But we were able to reproduce the case when `videoInput.requestMediaDataWhenReady` still working after cancelling.
> 
> I'm investigating the case.

@larryonoff  The block in `videoInput.requestMediaDataWhenReady` **should** be called after cancelling, that is by design, it **should not** be called after the `completion` handler.

Did you mean that the `videoInput.requestMediaDataWhenReady` block still get called after the `completion` handler?

**Comment by larryonoff** [comment]
`videoInput.requestMediaDataWhenReady` called repeatedly after `cancel`.

PS. As far as I understand you, `cancel` triggers `completion` but not at once.

**Comment by larryonoff** [comment]
@YuAo the issue still exists.

`videoInput.requestMediaDataWhenReady` reports the data when `self` is uninitialized.

```swift
            var sessionForVideoEncoder: AssetExportSession? = self
            videoInput.requestMediaDataWhenReady(on: self.queue) { [unowned videoInput] in
                guard let session = sessionForVideoEncoder else { return }
                if !session.encode(from: videoOutput, to: videoInput) {
                    videoCompleted = true
                    sessionForVideoEncoder = nil
                    if audioCompleted {
                        session.finish(completionHandler: completion)
                    }
                }
            }
```

**Comment by larryonoff** [comment]
maybe this will help Screen Shot 2020-07-16 at 14 44 47

**Comment by larryonoff** [comment]
I see now. All sessions are canceled, but with huge delay. But if I start -> cancel -> start -> cancel quick one-by-one. I receive  the following error:

```
Optional<Error>
  - some : Error Domain=AVFoundationErrorDomain Code=-11840 "Cannot Encode" UserInfo={NSLocalizedDescription=Cannot Encode, NSUnderlyingError=0x28053d680 {Error Domain=NSOSStatusErrorDomain Code=-12915 "(null)"}, NSLocalizedRecoverySuggestion=Stop any other actions that encode media and try again., NSLocalizedFailureReason=The encoder required for this media is busy.}
```

**Comment by larryonoff** [comment]
I just investigated the issue that this what I've found:

- `cancel` calls `reader.cancelReading()`

- `audioInput.requestMediaDataWhenReady` running. if `videoCompleted = false` finish not called until audio encoding completed
- `videoInput.requestMediaDataWhenReady` running. if `audioCompleted = false` finish not called until video encoding completed

The cases above are the cases that I'm facing all the time.

**Comment by larryonoff** [comment]
@YuAo what do you think about?

```swift
                    if audioCompleted || cancelled {
                        session.finish(completionHandler: completion)
                    }

                    if videoCompleted || cancelled {
                        session.finish(completionHandler: completion)
                    }
```

**Comment by YuAo** [comment]
@larryonoff Yes, I see the problem. The test asset I'm using does not contain audio tracks, so the tests passed.

**Comment by YuAo** [comment]
Added a new commit to fix this.

**Comment by larryonoff** [comment]
checking

**Comment by larryonoff** [comment]
It works now! Thank you!

**Comment by YuAo** [comment]
Updated the test asset with a file that contains audio track.

**Comment by larryonoff** [comment]
@YuAo maybe it would be great to add test without only audio and only video tracks?

**Comment by YuAo** [comment]
@larryonoff The test asset now have both audio and video tracks.

**Comment by YuAo** [comment]
@larryonoff Yes. However we do not need additional test assets. We can write something in the test target that only exports video/audio track from the current test asset. Then use the exported file to run more video/audio only tests.

I'll consider adding these tests later.

**Comment by larryonoff** [comment]
I undestand. So looking forward to the merge :)

**Comment by YuAo** [comment]
Released 1.0.3. You can track the CocoaPods update here: https://github.com/MetalPetal/VideoIO/runs/877907799?check_suite_focus=true

**Pull request merged**
